version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MGMT_KEY}
        databases:
          default:
            connector: postgres
            host: prisma-2-instance-1.cxqiy9guhvym.us-west-2.rds.amazonaws.com
            database: ru_prisma_1
            schema: public
            user: postgres
            password: zODzbaJWKHN59Io7rmfI
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true